# Generated by Django 4.2.7 on 2025-12-01 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_file_size_mb', models.IntegerField(default=100)),
                ('supported_formats', models.JSONField(default=list)),
                ('api_key_required', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('rate_limit_per_hour', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=20)),
                ('original_url', models.URLField(max_length=2048)),
                ('video_title', models.CharField(blank=True, max_length=500)),
                ('video_description', models.TextField(blank=True)),
                ('video_duration', models.DurationField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('downloaded_file', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('quality', models.CharField(choices=[('low', 'Low (360p)'), ('medium', 'Medium (720p)'), ('high', 'High (1080p)'), ('highest', 'Highest Available')], default='high', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.videodownload')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['user', 'created_at'], name='downloader__user_id_ee2be5_idx'),
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['status'], name='downloader__status_25f5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['platform'], name='downloader__platfor_203fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['user', 'downloaded_at'], name='downloader__user_id_c19900_idx'),
        ),
    ]
